FROM hummingbot/hummingbot:latest

USER root
COPY scripts/management_trading_snapshot.py /home/hummingbot/scripts/management_trading_snapshot.py
COPY hummingbot/connector/exchange/binance/binance_exchange.py /home/hummingbot/hummingbot/connector/exchange/binance/binance_exchange.py
COPY controllers/market_making/dman_maker_v3_macro.py /home/hummingbot/controllers/market_making/dman_maker_v3_macro.py
COPY hummingbot/strategy_v2/executors/dca_executor/data_types.py /home/hummingbot/hummingbot/strategy_v2/executors/dca_executor/data_types.py
COPY hummingbot/strategy_v2/executors/dca_executor/dca_executor.py /home/hummingbot/hummingbot/strategy_v2/executors/dca_executor/dca_executor.py
